### ISSUE TITLE
Error saat diinstall

### ISSUE THREAD

**Issue by haqimkq** [hoaaah/bossan#2]
mohon petunjuk cara instalnya bang,, krna dah nyoba gagal

**Comment by hoaaah** [comment]
Mohon informasi lebih jelas mengenai error dan apakah proses instalasi sudah dilakukan sesuai petunjuk yang ada?

**Comment by haqimkq** [comment]
munculnya begini bang..

Warning: require_once(C:\xampp\htdocs\lkp\bossan-master\_protected\vendor/composer/autoload_real.php): failed to open stream: No such file or directory in C:\xampp\htdocs\lkp\bossan-master\_protected\vendor\autoload.php on line 5

Fatal error: require_once(): Failed opening required 'C:\xampp\htdocs\lkp\bossan-master\_protected\vendor/composer/autoload_real.php' (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\lkp\bossan-master\_protected\vendor\autoload.php on line 5


![bosstan](https://user-images.githubusercontent.com/44763080/56800280-d7da8d00-6844-11e9-9790-faf07664f0e0.png)

**Comment by hoaaah** [comment]
Berarti belum menjalankan 
```
composer update
```

**Comment by haqimkq** [comment]
Udah dapat bang, masalahnya di php. Php saya versi 5.5 akhirnya saya upgrade,,
terakhir permasalahan dikonfigurasi database,,
padahal sudah sesuai tetapi masih error

" Tidak ada koneksi. Aplikasi membutuhkan koneksi internet pada server "

![yii](https://user-images.githubusercontent.com/44763080/56843490-c7b9c080-68cb-11e9-9852-1c23eb07b2ba.png)
![yii2](https://user-images.githubusercontent.com/44763080/56843494-cb4d4780-68cb-11e9-8d10-78cbfaba64c0.png)
![yii3](https://user-images.githubusercontent.com/44763080/56843497-ce483800-68cb-11e9-9660-2cfbd13f2116.png)

**Comment by hoaaah** [comment]
Seperti pesannya, aplikasinya harus online karena banyak make assets yg online. Lengkapnya silakan email ke heru@belajararief.com dan jangan lupa sebutkan asal instansi/nama sekolah ya sebagai bahan informasi buat saya jg

**Comment by herdotjazzy** [comment]
jadi langkah selanjutnya gimana pak
